-- MySQL Script generated by MySQL Workbench
-- Sat Nov 23 16:38:08 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Cinema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Cinema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Cinema` DEFAULT CHARACTER SET utf8 ;
USE `Cinema` ;

-- -----------------------------------------------------
-- Table `ADM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`ADM` (
  `idADM` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `CPF` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idADM`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `CPF` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sessao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`Sessao` (
  `idSessao` INT NOT NULL AUTO_INCREMENT,
  `Sala` VARCHAR(45) NOT NULL,
  `Horario` DATETIME NOT NULL,
  `Filme` VARCHAR(45) NOT NULL,
  `Cinema` VARCHAR(45) NOT NULL,
  `Capacidade` INT NOT NULL,
  PRIMARY KEY (`idSessao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`Compra` (
  `CompraCliente` INT NOT NULL,
  `SessaoCompra` INT NOT NULL,
  `Quantidade` INT NOT NULL,
  INDEX `fk_Compra_Cliente1_idx` (`CompraCliente` ASC) VISIBLE,
  INDEX `fk_Compra_Sessao1_idx` (`SessaoCompra` ASC) VISIBLE,
  CONSTRAINT `fk_Compra_Cliente1`
    FOREIGN KEY (`CompraCliente`)
    REFERENCES `Cinema`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Compra_Sessao1`
    FOREIGN KEY (`SessaoCompra`)
    REFERENCES `Cinema`.`Sessao` (`idSessao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;